### PR TITLE
Add Zitadel Strategy and implement PKCE

### PR DESCRIPTION
**Pull request by tommasop**
I added a strategy for zitadel.

Zitadel reccommends PKCE with no auth method.

I made changes also to OIDC and Oauth2 strategies to implment PKCE with no auth method for all strategies.

I added tests only for zitadel.

### CODE REVIEW

**Comment by danschultzer** [comment]
Thanks, I've pushed two PR's that deals with public client auth, and have rebased this PR. If you don't mind I'll force push to this PR and do a few follow up commits to streamline the flow.

**Comment by tommasop** [comment]
Absolutely, no problem on my side

**Comment by danschultzer** [comment]
We can leverage much of the OIDC strategy for this. I've condensed it down to what seems to be the absolute necessary. Can you try this out to confirm it works? I tested this with a dummy zitadel account, and it works correctly for me.

**Comment by tommasop** [comment]
I'll give it a try and report back here. Thanks for your work!

**Comment by danschultzer** [comment]
I've merged this PR as it was holding up some refactors that I'm doing. Still, let me know if there are any issues with it. I'll get a new release out shortly.

**Pull request merged**
